version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: retta-front/Dockerfile  # ← Builda Vue + Laravel unificado
    ports:
      - "8000:8000"
    volumes:
      - .env.railway:/var/www/.env
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: retta  
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: laravel 
      MYSQL_PASSWORD: secret123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
