FROM composer:2.8 AS vendor
WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader

FROM php:8.2-fpm-alpine
WORKDIR /var/www

RUN apk add --no-cache \
        libpng-dev \
        libjpeg-turbo-dev \
        libzip-dev \
        oniguruma-dev \
        icu-dev \
    && docker-php-ext-configure zip \
    && docker-php-ext-install \
        pdo_mysql mbstring exif pcntl bcmath zip gd intl

COPY --from=vendor /app/vendor ./vendor

COPY . .

RUN chown -R www-data:www-data \
        storage bootstrap/cache

EXPOSE 9000

CMD ["php-fpm"]
